### ISSUE TITLE
XELK Layout Option Controls

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/ipyelk#19]
Enhance networkx transformer for finer grained control for attaching ELK layout options. 
 See https://www.eclipse.org/elk/reference/options.html for some possible option choices.

**Comment by nrbgt** [comment]
Any concrete examples from the playground?

**Comment by dfreeman06** [comment]
You can see the start of these examples in: https://github.com/jupyrdf/ipyelk/blob/layout_options_widgets/examples/102_layout_options.ipynb

**Comment by dfreeman06** [comment]
Investigate improved LayoutOptions Widget Placement
https://github.com/jupyrdf/ipyelk/pull/15#issuecomment-714488310
