### ISSUE TITLE
🍱 Add an ElkBox

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyelk#40]
## Elevator Pitch
Make a `Box` subclass which uses the position of Elk nodes to place its `children`. 

## Motivation
For some kinds of interaction, it would be interesting to put interactive elements directly on an elk diagram.

## Who cares?

With a real plotting library (as a demo dependency) on the widget bus, e.g. `bqplot`, we could show things like signals being transformed based on inputs, e.g. a slider:

```
|-----------------|    |-----------------|
|                 |    |     --          |
| X ----O---- 0.3 []--[]    /  \         |
|                 |    |----     --------|
|-----------------|    |-----------------|
```

## Design Considerations

The python side of the house would probably just require a `child_nodes = T.Dict()` that mapped each child (or the index in `children`, lighter-weight) to the `id` of a node (or a label or port, i guess).

The typescript side will be... weird. We have this over on [wxyz](https://github.com/deathbeds/wxyz/blob/master/src/ts/wxyz-svg/src/widgets/svg.ts), which was (grossly, much `any`) ported from [ipylayouts](https://github.com/openseat/ipylayoutwidgets/blob/master/ipylayoutwidgets/static/ipylayoutwidgets/js/SVGLayoutBoxView.js). We can repurpose a lot of this, and replace a good deal of the expensive DOM measurement code with `_mark_layouts` and the root `<g transform="scale(z) translate(x, y)">`. Unlike that, this would allow for elements that are off-canvas, so the box DOM might be something like:

```html
<div class="p-Widget p-Panel jupyter-widgets widget-container widget-box widget-vbox styled-widget-140473608868624 jp-ElkBoxView" style="overflow: hidden;">
  <div class="p-Widget jp-ElkView"></div>
  <div class="p-Widget jp-FloatSlider" 
          style="position: absolute; left: 50px; top: 50px; zoom: 0.5"; width: 50px; height: 20px;"></div>
</div>
```

We would likely not publish the details back to the kernel, unless asked, as this would be doing LOTS of calculations during a pan/zoom interaction... indeed, we may want to hide the elements altogether until the DOM "cools off".

**Comment by dfreeman06** [comment]
Example of attaching a jupyterlab widget to an elk node.
* See sliders example in https://github.com/jupyrdf/ipyelk/blob/0.3.x/examples/12_Node_Menagerie.ipynb
* https://github.com/jupyrdf/ipyelk/blob/master/src/sprotty/views/node_views.tsx#L232
* https://github.com/jupyrdf/ipyelk/blob/master/src/sprotty/renderer.ts#L63
