### ISSUE TITLE
release ipyelk 0.3.0

### ISSUE THREAD

**Issue by nrbgt** [jupyrdf/ipyelk#69]
- [x] features
  - [x] #60: shapes, etc. 
- [x] infrastructure
- [x] docs
  - [x] #71: update readme 
    - [x] some new screenshots (maybe a wide table of three?)
  - [x] #68: update changelog
  - [x] #64: initial readthedocs
  - [x] #71: logo    
- [x] pick a funny new deer species
  - Megaloceros giganteus
- [x] validate binder 
- [x] tag
- [x] release on
  - [x] pypi
  - [x] npm
- [x] handle conda-forge update
- [x] make `0.3.x` branch
- [x] bump to next working version, e.g. `0.3.1`
- [x] update [release procedure](https://github.com/jupyrdf/ipyelk/blob/master/CONTRIBUTING.md#releasing) with lessons learned

**Comment by dfreeman06** [comment]
proposing for name `Megaloceros giganteus` due to it's large shapely antlers.
