### ISSUE TITLE
doit tasks 

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/ipyelk#79]
Developing off master. Running `doit lab` after a `git clean -xdf` results in everything building with no errors and lab starting. However, inside the example notebooks jupyterlab cannot find the diagram widget with the error:
```
Module @jupyrdf/jupyter-elk, semver range 1.0.1 is not registered as a widget module
```
It looks like the `ipyelk` extension isn't registered/being discovered. `!jupyter labextension list` only lists bqplot and the widget-manager.

**Comment by dfreeman06** [comment]
Looks like we need a task to add a symbolic link to the local extension (or I am missing the task where that is currently generated).

**Comment by nrbgt** [comment]
This is the [key task line](https://github.com/jupyrdf/ipyelk/blob/master/dodo.py#L228):

```
        yield _ok(
            dict(
                name="labext",
                actions=[[*P.APR_DEFAULT, *P.LAB_EXT, "develop", "--overwrite", "."]],
                file_dep=[P.NPM_TGZ, P.OK_PIP_INSTALL],
            ),
            P.OK_LABEXT,
        )
```

By default, it _doesn't_ run that, but rather the "real" install... because I don't _think_ you can't _release_ from a "dirty" watch build. I think `doit watch` does require that file, though.
