### ISSUE TITLE
Connector Shapes in Firefox

### ISSUE THREAD

**Issue by sanbales** [jupyrdf/ipyelk#84]
The connector ends in Firefox are cropped to a half of the image.

This happens on Windows and Linux versions of Firefox.  Works fine in Chrome.
 
![image](https://user-images.githubusercontent.com/1438114/112851713-3fc13000-9079-11eb-9cc0-9cc891a1642c.png)

**Comment by dfreeman06** [comment]
CSS Fix should be in #88.
