### ISSUE TITLE
overhauling elements / shapes /symbols api

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/ipyelk#86]
The usability can be improved with a clearer api surface area.

- [x] promote the `contrib.elements` to `ipyelk.elements`
- [x] adding metadata to `BaseElement` 
- [x] fix hover exception for some elk ids not in the transformer registry
- [x] standardizing transformer registry items to `Mark`s
- [x] convert `Compound` class to `MarkFactory`
- [x] rework `Symbol` and `Shape` schema and api.
- [x] rename `ConnectorDef` aka `ElementSymbol` offset fields

**Comment by sanbales** [comment]
Changing these `ValueErrors` to `ElkRegistryErrors` would be a nice cheap quality of life improvement:

- [ ] https://github.com/jupyrdf/ipyelk/blob/master/py_src/ipyelk/app.py#L90

- [ ] https://github.com/jupyrdf/ipyelk/blob/master/py_src/ipyelk/app.py#L113
