### ISSUE TITLE
release ipyelk 2.0.0a0

### ISSUE THREAD

**Issue by dfreeman06** [jupyrdf/ipyelk#93]
Alpha Release for ipyelk 2.0

- [x] dependencies
  - [x] pydantic
- [x] bug fixes
- [x] infrastructure
- [x] docs
  - [x] update changelog
- [x] pick a funny new deer species
  - save for 2.0
- [x] validate binder
  - [ ] conda: https://gist.github.com/nrbgt/391ef0904fe520efd2a28d8cdc761978
  - [ ] pip: https://gist.github.com/nrbgt/8e21f87c63296948a3e1e6c69c1742dd
- [x] tag
- [x] release on
  - [x] pypi
  - [x] npm
- [x] handle conda-forge update
  - [x] https://github.com/conda-forge/ipyelk-feedstock/pull/7
- [x] update [release procedure](https://github.com/jupyrdf/ipyelk/blob/master/CONTRIBUTING.md#releasing) with lessons learned
- [x] #92: bump to next working version e.g. `2.0.0a1`

**Comment by zwelz3** [comment]
What is the proper way to specify channel/etc, in order to add this to e.g. `requirement.txt` or `anaconda-project`?

**Comment by zwelz3** [comment]
> What is the proper way to specify channel/etc, in order to add this to e.g. `requirement.txt` or `anaconda-project`?

Instructions are [here](https://anaconda.org/conda-forge/ipyelk).
> conda install -c conda-forge/label/ipyelk_alpha ipyelk
